language: node_js
node_js:
- '6'
sudo: required
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm config set registry http://registry.npmjs.org/
  - npm config set spin false
  - git config user.name 'travis-build'

install:
  - yarn install

script:
  - npm test

notifications:
  email: false
